// web-v4/src/lib/components/forms/VehicleForm.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import Button from '$lib/components/common/Button.svelte';
	import Field from '$lib/components/common/Field.svelte';
	import Input from '$lib/components/common/Input.svelte';
	import type { Vehicle, VehiclePreferences } from '$lib/data/vehicles';
	import type { FormError } from '$lib/utils/form';

	type DistanceUnit = 'mi' | 'km' | 'hr' | 'nmi';

	interface Props {
		errors?: FormError[];
		values?: Partial<Vehicle>;
		action?: string;
	}

	let { errors = [], values, action }: Props = $props();
</script>

<form method="post" {action} use:enhance class="flex flex-col gap-6">
	<fieldset class="flex flex-col gap-4">
		<Field name="name" label="Name" {errors} required>
			<Input name="name" value={values?.name} required />
		</Field>

		<Field name="vin" label="VIN" {errors} hint="VIN is optional but recommended">
			<Input name="vin" value={values?.vin ?? ''} />
		</Field>

		<Field name="color" label="Color" {errors}>
			<input
				type="color"
				name="color"
				value={values?.color ?? '#cccccc'}
				class="w-full h-8 rounded-md border border-ink-200 bg-canvas cursor-pointer"
			/>
		</Field>

		<Field name="distanceUnit" label="Distance Unit" {errors} required>
			<select
				name="distanceUnit"
				class="w-full px-3 py-2 h-8 text-sm rounded-md border border-ink-200 bg-canvas text-ink-900"
			>
				<option value="mi" selected={values?.distanceUnit === 'mi'}>Miles</option>
				<option value="km" selected={values?.distanceUnit === 'km'}>Kilometers</option>
				<option value="hr" selected={values?.distanceUnit === 'hr'}>Hours</option>
				<option value="nmi" selected={values?.distanceUnit === 'nmi'}>Nautical Miles</option>
			</select>
		</Field>
	</fieldset>

	<hr class="border-ink-200" />

	<fieldset class="flex flex-col gap-4">
		<legend class="font-semibold">Preferences</legend>

		<label class="flex items-center gap-3 cursor-pointer">
			<input type="checkbox" name="preferences.enableCost" checked={values?.preferences?.enableCost ?? true} class="accent-brand" />
			<div>
				<span class="font-medium">Enable cost</span>
				<p class="text-sm text-ink-500">Show cost column in History and cost field in form.</p>
			</div>
		</label>

		<label class="flex items-center gap-3 cursor-pointer">
			<input type="checkbox" name="preferences.sendReminderEmails" checked={values?.preferences?.sendReminderEmails ?? true} class="accent-brand" />
			<div>
				<span class="font-medium">Send reminder emails</span>
				<p class="text-sm text-ink-500">Receive an email for upcoming reminders 2 weeks before and on the due date.</p>
			</div>
		</label>

		<label class="flex items-center gap-3 cursor-pointer">
			<input type="checkbox" name="preferences.sendPromptForRecords" checked={values?.preferences?.sendPromptForRecords ?? true} class="accent-brand" />
			<div>
				<span class="font-medium">Send prompt for records email</span>
				<p class="text-sm text-ink-500">Receive an email asking if you recently performed service based on your record history.</p>
			</div>
		</label>

		<label class="flex items-center gap-3 cursor-pointer">
			<input type="checkbox" name="preferences.showMileageAdjustmentRecords" checked={values?.preferences?.showMileageAdjustmentRecords ?? true} class="accent-brand" />
			<div>
				<span class="font-medium">Show mileage adjustment records</span>
				<p class="text-sm text-ink-500">Show mileage adjustment records in History.</p>
			</div>
		</label>
	</fieldset>

	{#if values?.id}
		<hr class="border-ink-200" />

		<fieldset class="flex flex-col gap-4">
			<label class="flex items-center gap-3 cursor-pointer">
				<input type="checkbox" name="retired" checked={values?.retired} class="accent-brand" />
				<div>
					<span class="font-medium">Retire</span>
					<p class="text-sm text-ink-500">Hide this vehicle from the list and stop sending reminders.</p>
				</div>
			</label>
		</fieldset>
	{/if}

	<div class="flex gap-3">
		<Button type="submit">Save {values?.name || 'vehicle'}</Button>
	</div>
</form>

// web/src/components/forms/VehicleForm/VehicleForm.tsx
import {
    Box,
    FormControl,
    FormHelperText,
    FormLabel,
    Input,
    Select,
    Stack,
    StackDivider,
    Switch,
    useColorModeValue,
} from '@chakra-ui/react';
import DestroyButton from 'components/common/DestroyButton';
import FormErrors from 'components/common/FormErrors';
import FormButton from 'components/common/FormButton';
import VehicleColorIndicator from 'components/VehicleColorIndicator';
import useFormData from 'hooks/useFormData';
import useMutation from 'hooks/useMutation';
import { useRouter } from 'next/router';
import * as vehicles from 'queries/vehicles';
import React from 'react';
import { vehiclePath, vehiclesPath } from 'utils/resources';
import DangerZone from 'components/common/DangerZone';
import FormSection from 'components/common/FormSection';

export interface VehicleFormProps {
    vehicle?: API.Vehicle;
}

export const VehicleForm: React.FC<VehicleFormProps> = ({ vehicle }) => {
    const router = useRouter();
    const borderColor = useColorModeValue('gray.200', 'gray.600');

    const { formData, register } = useFormData(
        {
            name: '',
            vin: '',
            distanceUnit: 'mi',
            ...vehicle,
            preferences: {
                enableCost: true,
                sendReminderEmails: true,
                sendPromptForRecords: true,
                showMileageAdjustmentRecords: true,
                ...vehicle?.preferences,
            },
        },
        [vehicle],
    );

    const {
        mutate: createOrUpdateVehicle,
        isProcessing,
        error,
    } = useMutation(vehicles.createOrUpdateVehicle, {
        onSuccess(nextVehicle) {
            router.replace(vehiclePath(nextVehicle.id));
        },
    });

    const { mutate: destroyVehicle } = useMutation(vehicles.destroyVehicle, {
        onSuccess() {
            router.replace(vehiclesPath());
        },
    });

    const handleDeleteVehicle = (e) => {
        e.preventDefault();
        if (!vehicle) return;
        destroyVehicle(vehicle.id);
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        createOrUpdateVehicle(formData);
    };

    return (
        <>
            <form onSubmit={handleSubmit}>
                {error && 'errors' in error && (
                    <FormErrors errors={error.errors} />
                )}

                <FormSection>
                    <FormControl id="name" mb={4} isRequired>
                        <FormLabel>Name</FormLabel>
                        <Input type="text" {...register('name')} />
                    </FormControl>

                    <FormControl id="vin" mb={4}>
                        <FormLabel>VIN</FormLabel>
                        <Input type="text" {...register('vin')} />
                        <FormHelperText>
                            VIN is optional but recommended
                        </FormHelperText>
                    </FormControl>

                    <FormControl id="edit-color" mb={4} overflow="hidden">
                        <FormLabel>
                            Color
                            <Box mt={2}>
                                <VehicleColorIndicator
                                    color={formData.color}
                                    size={10}
                                    borderWidth={3}
                                />
                            </Box>
                        </FormLabel>
                        <Box position="absolute" left="-100%">
                            <input
                                id="edit-color"
                                type="color"
                                {...register('color')}
                            />
                        </Box>
                    </FormControl>

                    <FormControl id="distanceUnit" mb={4} isRequired>
                        <FormLabel>Distance Unit</FormLabel>
                        <Select {...register('distanceUnit')}>
                            <option value="mi">miles</option>
                            <option value="km">kilometers</option>
                            <option value="hr">hours</option>
                            <option value="nmi">nautical miles</option>
                        </Select>
                    </FormControl>
                </FormSection>

                <FormSection heading="Preferences">
                    <Stack
                        spacing={4}
                        divider={<StackDivider borderColor={borderColor} />}
                    >
                        <FormControl display="flex" alignItems="center">
                            <FormLabel
                                flex={1}
                                pr={4}
                                m={0}
                                htmlFor="preferences.enableCost"
                            >
                                Enable cost
                                <FormHelperText mt={0}>
                                    Show cost column in History and cost field
                                    in form.
                                </FormHelperText>
                            </FormLabel>
                            <Switch
                                colorScheme="green"
                                {...register('preferences.enableCost')}
                            />
                        </FormControl>

                        <FormControl display="flex" alignItems="center">
                            <FormLabel
                                flex={1}
                                pr={4}
                                m={0}
                                htmlFor="preferences.sendReminderEmails"
                            >
                                Send reminder emails
                                <FormHelperText mt={0}>
                                    Receive an email for upcoming reminders 2
                                    weeks before and on the due date.
                                </FormHelperText>
                            </FormLabel>
                            <Switch
                                colorScheme="green"
                                {...register('preferences.sendReminderEmails')}
                            />
                        </FormControl>

                        <FormControl display="flex" alignItems="center">
                            <FormLabel
                                flex={1}
                                pr={4}
                                m={0}
                                htmlFor="preferences.sendPromptForRecords"
                            >
                                Send prompt for records
                                <FormHelperText mt={0}>
                                    Receive an email asking if you recenty
                                    performed service based on your record
                                    history.
                                </FormHelperText>
                            </FormLabel>
                            <Switch
                                colorScheme="green"
                                {...register(
                                    'preferences.sendPromptForRecords',
                                )}
                            />
                        </FormControl>

                        <FormControl display="flex" alignItems="center">
                            <FormLabel
                                flex={1}
                                pr={4}
                                m={0}
                                htmlFor="preferences.showMileageAdjustmentRecords"
                            >
                                Show mileage adjustment records
                                <FormHelperText mt={0}>
                                    Show mileage adjustment records in History.
                                </FormHelperText>
                            </FormLabel>
                            <Switch
                                colorScheme="green"
                                {...register(
                                    'preferences.showMileageAdjustmentRecords',
                                )}
                            />
                        </FormControl>
                    </Stack>
                </FormSection>

                <FormButton type="submit" isProcessing={isProcessing} />
            </form>

            {Boolean(vehicle) && (
                <DangerZone>
                    <DestroyButton onConfirm={handleDeleteVehicle}>
                        Delete vehicle
                    </DestroyButton>
                </DangerZone>
            )}
        </>
    );
};

export default VehicleForm;
