// web-v4/src/lib/components/vehicles/VehicleColorIndicator.svelte
<script lang="ts">
	import { getColorPalette } from '$lib/utils/colors';

	interface Props {
		color?: string | null;
		size?: number;
	}

	let { color = '#cccccc', size = 7 }: Props = $props();

	let resolvedColor = $derived(color ?? '#cccccc');
	let palette = $derived(getColorPalette(resolvedColor));
	let background = $derived(`linear-gradient(0deg, ${palette[600]} 50%, ${resolvedColor} 50%)`);
</script>

<div
	class="rounded-full border-2 shrink-0"
	style="width: {size * 0.25}rem; height: {size *
		0.25}rem; background: {background}; border-color: {palette[400]};"
></div>

// web/src/components/VehicleColorIndicator/VehicleColorIndicator.tsx
import { Box } from '@chakra-ui/react';
import React from 'react';
import getColorPalette from 'utils/colors';

export interface VehicleColorIndicatorProps {
    color: string | null | undefined;
    size?: number;
    borderWidth?: number;
}

export const VehicleColorIndicator: React.FC<VehicleColorIndicatorProps> = ({
    color,
    size = 6,
    borderWidth = 2,
}) => {
    const bg = color || '#fafafa';
    const p = getColorPalette(bg);

    const background = `linear-gradient(0deg, ${p[600]} 50%, ${bg} 50%)`;

    return (
        <Box
            bg={background}
            borderRadius="full"
            borderWidth={borderWidth}
            borderColor={p[400]}
            w={size}
            h={size}
        />
    );
};

export default VehicleColorIndicator;
