// web/src/components/forms/ReminderForm/ReminderForm.tsx
import {
    Alert,
    AlertIcon,
    Box,
    FormControl,
    FormHelperText,
    FormLabel,
    Input,
    Select,
    Text,
} from '@chakra-ui/react';
import DatePicker from 'components/common/DatePicker';
import DestroyButton from 'components/common/DestroyButton';
import FormErrors from 'components/common/FormErrors';
import FormButton from 'components/common/FormButton';
import { addMonths } from 'date-fns';
import useFormData from 'hooks/useFormData';
import useMutation, { mutate } from 'hooks/useMutation';
import { capitalize } from 'lodash';
import { useRouter } from 'next/router';
import { clientAPI } from 'queries/config';
import * as reminders from 'queries/reminders';
import { vehicleAPIPath } from 'queries/vehicles';
import React, { useEffect, useState } from 'react';
import { formatDateISO, intlFormatDate, parseDateUTC } from 'utils/date';
import { mileageFieldHelpers } from 'utils/form';
import lang from 'utils/lang';
import { reminderPath, vehiclePath } from 'utils/resources';
import { formatMileage } from 'utils/vehicle';
import FormSection from 'components/common/FormSection';
import DangerZone from 'components/common/DangerZone';

export interface NewReminderFormProps {
    vehicleId: API.RecordID;
    minMileage?: number;
    distanceUnit: API.DistanceUnit | undefined;
    formValues?: reminders.ReminderParams;
}

export const ReminderForm: React.FC<NewReminderFormProps> = ({
    formValues,
    vehicleId,
    minMileage = 0,
    distanceUnit = 'mi',
}) => {
    const router = useRouter();
    const [estimatedDate, setEstimatedDate] = useState<Date | null>(null);

    const { formData, register, setValue } = useFormData(
        {
            date: formatDateISO(addMonths(new Date(), 6)),
            notes: '',
            reminderType: '',
            mileage: '',
            ...formValues,
        },
        [formValues],
    );

    const {
        mutate: createOrUpdateReminder,
        isProcessing,
        error,
    } = useMutation(reminders.createOrUpdateReminder, {
        onSuccess() {
            mutate(vehicleAPIPath(vehicleId));
            if (formValues?.id) {
                router.replace(`${reminderPath(vehicleId, formValues?.id)}`);
            } else {
                router.replace(`${vehiclePath(vehicleId)}#panel=1`);
            }
        },
    });

    const { mutate: destroyReminder } = useMutation(reminders.destroyReminder, {
        onSuccess() {
            router.replace(`${vehiclePath(vehicleId)}#panel=1`);
        },
    });

    useEffect(() => {
        const estimateReminderDate = async (
            params: reminders.EstimateReminderParams,
        ) => {
            try {
                const { reminderDate } = await reminders.estimateReminderDate(
                    clientAPI,
                    vehicleId,
                    params,
                );
                if (reminderDate) {
                    setEstimatedDate(parseDateUTC(reminderDate));
                }
            } catch (err) {
                console.error(err);
            }
        };

        const mileage = Number(formData.mileage);

        if (mileage > 0 && mileage >= minMileage) {
            estimateReminderDate({
                mileage,
                date: formData.date,
                reminderType: formData.reminderType as API.ReminderType,
            });
        } else {
            setEstimatedDate(null);
        }
    }, [minMileage, formData.mileage, formData.date, formData.reminderType]);

    const handleSubmit = (e) => {
        e.preventDefault();
        createOrUpdateReminder(vehicleId, formData);
    };

    const handleDelete = (e) => {
        e.preventDefault();
        if (!formValues) return;
        destroyReminder(vehicleId, formValues.id);
    };

    return (
        <form onSubmit={handleSubmit}>
            {error && 'errors' in error && <FormErrors errors={error.errors} />}

            <FormSection>
                <FormControl mb={4} id="note" isRequired>
                    <FormLabel>Note</FormLabel>
                    <Input type="text" {...register('notes')} autoFocus />
                </FormControl>

                <FormControl mb={4} id="reminderType">
                    <FormLabel>Remind me</FormLabel>
                    <Select {...register('reminderType')}>
                        <option value="">Don&apos;t remind me</option>
                        <option value="date_or_mileage">
                            On a date or mileage, whichever is first
                        </option>
                        <option value="date">On a date</option>
                        <option value="mileage">At a mileage</option>
                    </Select>
                </FormControl>

                {['date', 'date_or_mileage'].includes(
                    formData.reminderType as string,
                ) && (
                    <FormControl mb={4} id="date" isRequired>
                        <FormLabel>Date</FormLabel>
                        <input type="hidden" {...register('date')} />
                        <DatePicker
                            initialDate={parseDateUTC(formData.date as string)}
                            onChange={(date) =>
                                setValue('date', formatDateISO(date))
                            }
                        />
                    </FormControl>
                )}

                {['mileage', 'date_or_mileage'].includes(
                    formData.reminderType as string,
                ) && (
                    <FormControl mb={4} id="mileage" isRequired>
                        <FormLabel>
                            {capitalize(lang.mileageLabel[distanceUnit])}
                        </FormLabel>

                        <Input
                            {...register('mileage', mileageFieldHelpers)}
                            inputMode="numeric"
                            pattern="[0-9,]*"
                        />

                        {Boolean(minMileage) && (
                            <FormHelperText>
                                Minimum{' '}
                                {formatMileage(minMileage, distanceUnit)}
                            </FormHelperText>
                        )}
                    </FormControl>
                )}

                {estimatedDate &&
                    ['date_or_mileage', 'mileage'].includes(
                        formData.reminderType as string,
                    ) && (
                        <Alert status="info" variant="left-accent">
                            Estimated for {intlFormatDate(estimatedDate)}
                        </Alert>
                    )}
            </FormSection>

            <FormButton type="submit" isProcessing={isProcessing} />

            {Boolean(formValues?.id) && (
                <DangerZone>
                    <DestroyButton
                        confirmTitle="Please confirm delete"
                        confirmBody="You can't undo this action afterwards."
                        onConfirm={handleDelete}
                    >
                        Delete reminder
                    </DestroyButton>
                </DangerZone>
            )}
        </form>
    );
};

export default ReminderForm;

// web-v4/src/lib/components/forms/ReminderForm.svelte
<script lang="ts">
	import { enhance } from '$app/forms';
	import { addMonths } from 'date-fns';
	import Button from '$lib/components/common/Button.svelte';
	import Field from '$lib/components/common/Field.svelte';
	import Input from '$lib/components/common/Input.svelte';
	import InputGroup from '$lib/components/common/InputGroup.svelte';
	import NativeSelect from '$lib/components/common/NativeSelect.svelte';
	import { formatDateISO, intlFormatDate, parseDateUTC } from '$lib/utils/date';
	import { formatMileage, mileageLabel, MileageLabel } from '$lib/utils/vehicle';
	import { estimateReminderDate } from '$lib/data/reminders.remote';
	import type { Reminder, ReminderType } from '$lib/data/reminders';
	import type { Vehicle } from '$lib/data/vehicles';
	import type { FormError } from '$lib/utils/form';
	import { Alert } from '$lib';

	interface Props {
		vehicle: Vehicle;
		reminder?: Reminder;
		errors?: FormError[];
		action?: string;
		noEnhance?: boolean;
	}

	let { vehicle, reminder, errors = [], action, noEnhance = false }: Props = $props();

	let formErrors = $derived(errors.filter((e) => e.id === 'form'));

	let notes = $state(reminder?.notes ?? '');
	let reminderType = $state<ReminderType>(reminder?.reminderType ?? '');
	let date = $state(
		reminder?.date
			? formatDateISO(new Date(reminder.date))
			: formatDateISO(addMonths(new Date(), 6)),
	);
	let mileage = $state(reminder?.mileage?.toString() ?? '');

	let estimatedDate = $state<Date | null>(null);

	let mileageNum = $derived(Number(mileage));

	$effect(() => {
		const estimate = async () => {
			if (mileageNum > 0) {
				try {
					const data = await estimateReminderDate({
						vehicleId: String(vehicle.id),
						mileage: mileageNum,
						date,
						reminderType,
					});
					if (data.reminderDate) {
						estimatedDate = parseDateUTC(data.reminderDate);
					}
				} catch {
					estimatedDate = null;
				}
			} else {
				estimatedDate = null;
			}
		};
		estimate();
	});
</script>

<form
	method="POST"
	action={action ?? `/vehicles/${vehicle.id}/reminders${reminder ? `/${reminder.id}` : ''}`}
	use:enhance
	class="flex flex-col gap-6"
>
	{#if formErrors.length > 0}
		<div role="alert" class="p-3 rounded-md bg-negative/10 text-negative text-sm">
			{#each formErrors as e}
				<p>{e.title}</p>
			{/each}
		</div>
	{/if}

	<fieldset class="flex flex-col gap-4">
		<Field name="notes" label="Note" {errors} required>
			<Input name="notes" bind:value={notes} required />
		</Field>

		<Field name="reminderType" label="Remind me" {errors}>
			<NativeSelect
				name="reminderType"
				bind:value={reminderType}
				options={[
					{ value: '', label: "Don't remind me" },
					{ value: 'date_or_mileage', label: 'On a date or mileage, whichever is first' },
					{ value: 'date', label: 'On a date' },
					{ value: 'mileage', label: 'At a mileage' },
				]}
			/>
		</Field>

		{#if ['date', 'date_or_mileage'].includes(reminderType)}
			<Field name="date" label="Date" {errors} required>
				<Input type="date" name="date" bind:value={date} required />
			</Field>
		{/if}

		{#if ['mileage', 'date_or_mileage'].includes(reminderType)}
			<Field name="mileage" label={MileageLabel(vehicle.distanceUnit)} {errors} required>
				<InputGroup name="mileage" bind:value={mileage} inputmode="numeric">
					{#snippet endAddon()}{vehicle.distanceUnit}{/snippet}
				</InputGroup>
				{#if vehicle.estimatedMileage}
					<p class="text-sm text-ink-400">
						Estimated {mileageLabel(vehicle.distanceUnit)}
						{formatMileage(vehicle.estimatedMileage, vehicle.distanceUnit)}
					</p>
				{/if}
			</Field>
		{/if}

		{#if estimatedDate && ['date_or_mileage', 'mileage'].includes(reminderType)}
			<Alert variant="info">
				Estimated for {intlFormatDate(estimatedDate)}
			</Alert>
		{/if}
	</fieldset>

	<div class="flex gap-3">
		<Button type="submit">
			{reminder ? 'Update' : 'Create'} Reminder
		</Button>
	</div>
</form>
