// web-v4/src/lib/components/VehicleSortMenu.svelte
<script lang="ts">
	import type { Order, Sortable } from '$lib/data/vehicles';
	import {
		orderToHuman,
		vehicleSortOrderToHuman,
		vehicleSortStrategy,
		vehicleSortStrategyToHuman,
		type VehicleSortStrategy
	} from '$lib/utils/sortable';
	import { CheckIcon } from 'lucide-svelte';
	import DropdownMenu from './DropdownMenu.svelte';

	interface Props {
		onSelect?: (value: Sortable) => void;
		sortable?: Sortable;
	}

	let { sortable = ['created_at', 'desc'], onSelect }: Props = $props();

	const [sortStrategy, sortOrder] = sortable;
</script>

<DropdownMenu
	label={`Order By: ${orderToHuman(sortable)} ${vehicleSortStrategyToHuman[sortStrategy]}`}
	size="sm"
	variant="ghost"
	align="end"
>
	{#each Object.keys(vehicleSortStrategy) as value (value)}
		<li>
			<button
				role="menuitemradio"
				aria-checked={value === sortStrategy}
				onclick={() => onSelect?.([value as VehicleSortStrategy, sortOrder])}
			>
				<CheckIcon size={16} />
				{vehicleSortStrategyToHuman[value as VehicleSortStrategy]}
			</button>
		</li>
	{/each}
	<li role="separator"></li>
	{#each ['asc', 'desc'] as order, i (order)}
		<li>
			<button
				role="menuitemradio"
				aria-checked={order === sortOrder}
				onclick={() => onSelect?.([sortStrategy, order as Order])}
			>
				<CheckIcon size={16} />
				{vehicleSortOrderToHuman[sortStrategy][i]}
			</button>
		</li>
	{/each}
</DropdownMenu>

// src/components/VehicleSortMenu/VehicleSortMenu.tsx
import { ChevronDownIcon } from '@chakra-ui/icons';
import {
    Button, Menu, MenuButton, MenuDivider, MenuItemOption, MenuList, MenuOptionGroup, useBreakpointValue,
} from '@chakra-ui/react';
import React from 'react';
import {
    Order,
    orderToHuman,
    vehicleSortOrderToHuman, vehicleSortStrategy, VehicleSortStrategy, vehicleSortStrategyToHuman,
} from 'utils/sortable';

export interface VehicleSortMenuProps {
    onChange: (value: [VehicleSortStrategy, Order]) => void;
    sortable: [VehicleSortStrategy, Order];
}

export const VehicleSortMenu: React.FC<VehicleSortMenuProps> = ({
    sortable,
    onChange: onChangeProp,
}) => {
    const size = useBreakpointValue({ sm: 'xs', base: 'sm' });
    const [sortStrategy, sortOrder] = sortable;

    return (
        <Menu>
            <MenuButton as={Button} size={size} rightIcon={<ChevronDownIcon />}>
                Order By:
                {' '}
                {orderToHuman(sortable)}
                {' '}
                {vehicleSortStrategyToHuman[sortStrategy]}
            </MenuButton>
            <MenuList zIndex={2}>
                <MenuOptionGroup
                    value={sortStrategy}
                    type="radio"
                    onChange={(v) => onChangeProp([v as VehicleSortStrategy, sortOrder])}
                >
                    {Object.keys(vehicleSortStrategy).map((value) => (
                        <MenuItemOption key={value} value={value}>
                            {vehicleSortStrategyToHuman[value]}
                        </MenuItemOption>
                    ))}
                </MenuOptionGroup>
                <MenuDivider />
                <MenuOptionGroup
                    value={sortOrder}
                    type="radio"
                    onChange={(v) => onChangeProp([sortStrategy, v as Order])}
                >
                    {vehicleSortOrderToHuman[sortStrategy].map((order, i) => (
                        <MenuItemOption
                            key={order}
                            value={i === 0 ? 'asc' : 'desc'}
                        >
                            {order}
                        </MenuItemOption>
                    ))}
                </MenuOptionGroup>
            </MenuList>
        </Menu>
    );
};

export default VehicleSortMenu;
