// web-v4/src/lib/components/vehicles/VehicleSortMenu.svelte
<script lang="ts">
	import Menu, { type OptionItem } from '$lib/components/common/Menu.svelte';
	import type { ButtonSize } from '$lib/components/common/Button.svelte';
	import type { Order, Sortable, VehicleSortStrategy } from '$lib/data/vehicles';
	import {
		orderToHuman,
		vehicleSortOrderToHuman,
		vehicleSortStrategy,
		vehicleSortStrategyToHuman,
	} from '$lib/utils/sortable';

	interface Props {
		sortable?: Sortable;
		size?: ButtonSize;
		onSelect?: (value: Sortable) => void;
	}

	let { sortable = ['created_at', 'desc'], size, onSelect }: Props = $props();

	let sortStrategy = $derived(sortable[0]);
	let sortOrder = $derived(sortable[1]);

	let optionItems = $derived<OptionItem[]>([
		...Object.keys(vehicleSortStrategy).map((value) => ({
			type: 'radio' as const,
			name: 'strategy',
			value,
			label: vehicleSortStrategyToHuman[value as VehicleSortStrategy],
			checked: value === sortStrategy,
			onCheckedChange: (checked: boolean) => {
				if (checked) onSelect?.([value as VehicleSortStrategy, sortOrder]);
			},
		})),
		{ type: 'separator' as const },
		...['asc', 'desc'].map((order, i) => ({
			type: 'radio' as const,
			name: 'order',
			value: order,
			label: vehicleSortOrderToHuman[sortStrategy][i],
			checked: order === sortOrder,
			onCheckedChange: (checked: boolean) => {
				if (checked) onSelect?.([sortStrategy, order as Order]);
			},
		})),
	]);
</script>

<Menu {optionItems} {size}>
	Order By: {orderToHuman(sortable)} {vehicleSortStrategyToHuman[sortStrategy]}
</Menu>

// web/src/components/VehicleSortMenu/VehicleSortMenu.tsx
import { ChevronDownIcon } from '@chakra-ui/icons';
import {
    Button,
    Menu,
    MenuButton,
    MenuDivider,
    MenuItemOption,
    MenuList,
    MenuOptionGroup,
    useBreakpointValue,
} from '@chakra-ui/react';
import React from 'react';
import {
    orderToHuman,
    vehicleSortOrderToHuman,
    vehicleSortStrategy,
    VehicleSortStrategy,
    vehicleSortStrategyToHuman,
} from 'utils/sortable';

export interface VehicleSortMenuProps {
    onChange: (value: [VehicleSortStrategy, API.Order]) => void;
    sortable: [VehicleSortStrategy, API.Order];
}

export const VehicleSortMenu: React.FC<VehicleSortMenuProps> = ({
    sortable,
    onChange: onChangeProp,
}) => {
    const size = useBreakpointValue({ sm: 'xs', base: 'sm' });
    const [sortStrategy, sortOrder] = sortable;

    return (
        <Menu>
            <MenuButton as={Button} size={size} rightIcon={<ChevronDownIcon />}>
                Order By: {orderToHuman(sortable)}{' '}
                {vehicleSortStrategyToHuman[sortStrategy]}
            </MenuButton>
            <MenuList zIndex={2}>
                <MenuOptionGroup
                    value={sortStrategy}
                    type="radio"
                    onChange={(v) =>
                        onChangeProp([v as VehicleSortStrategy, sortOrder])
                    }
                >
                    {Object.keys(vehicleSortStrategy).map((value) => (
                        <MenuItemOption key={value} value={value}>
                            {vehicleSortStrategyToHuman[value]}
                        </MenuItemOption>
                    ))}
                </MenuOptionGroup>
                <MenuDivider />
                <MenuOptionGroup
                    value={sortOrder}
                    type="radio"
                    onChange={(v) =>
                        onChangeProp([sortStrategy, v as API.Order])
                    }
                >
                    {vehicleSortOrderToHuman[sortStrategy].map((order, i) => (
                        <MenuItemOption
                            key={order}
                            value={i === 0 ? 'asc' : 'desc'}
                        >
                            {order}
                        </MenuItemOption>
                    ))}
                </MenuOptionGroup>
            </MenuList>
        </Menu>
    );
};

export default VehicleSortMenu;
